//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppSalon.Entities.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsClient
    {
        public int IDTagClient { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> TagID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
